//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public int User_ID { get; set; }
        public int Product_ID { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Order_Status { get; set; }
        public string Shipping_Address { get; set; }
        public string Payment_Method { get; set; }
        public decimal Total_Ammount { get; set; }
        public string Order_Details { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
